POST http://localhost:8080/posts
Content-Type: application/json

{
"content":  "hello",
"authorId":  0
}

###
GET http://localhost:8080/posts/0
Accept: application/json

###

###
PUT http://localhost:8080/posts
Content-Type: application/json

{
  "id" : 0,
  "contents": "조광일0"
}

###
DELETE http://localhost:8080/posts/0
Accept: application/json

###

